version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_server
    tty: true
    restart: always
    ports:
      - '80:8080'
    environment:
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - local
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    container_name: todo_line_db
    restart: always
    networks:
      - local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todo_line
networks:
  local:
    driver: bridge